Basico/Curso Basico de Django/premiosplatziapp/polls/urls.py
from django.shortcuts import render
from django.urls import path
from . import views 

# la razon de que sirva app_name= "polls" evitar confuciones futuras si yo en 
# premiosplatzi.urls.py cambio la url de "polls" por algun otro nombre que se me ocurra ("preguntas")
#todo el route se mantenie. 
# Pero aparacera el url nuevo 
app_name= "polls" #namespace

#para que esto funcione el archivo html debe 
# llevar 'polls:variable'. Variable es el nombre de la variable name que se encuentra en cada una de las path que se encuentran aca abajoo en pathpatterns . ejm path(name= 'detail')'. Entonces de debe ver asi con el ejemplo de detail: 
# 'polls:detail'



# la url se vera asi  
# http://127.0.0.1:8000/preguntas
# NombreDeLaURL_PuestaEn_premiosplatiziapp<int:id>/"<int:id>/detail/naruto"
# ejemplo:
# http://127.0.0.1:8000/preguntas/1//detail/naruto





urlpatterns =[
  # El archivo index,html se ejecto al acceder a la ruta raiz. ejectuta el codigo de views.index y muestra las preguntas. 
    
    # Function base views  
    # path ("", views.index, name="index"),
    # Function generic views
    
    path ("", views.IndexView.as_view(), name="index"),
    
      
    #   y dentro de este html atraves de la linea 
     # href="{% url 'polls:detail' question.id %}" 
    # accede al codigo de views.detail y crea un href (ojo no es el texto si no el hipervinculo)
     
     # Lo hacepreguntando por app_name= "polls" y busca finalmene a name='datail' en urlpatterns en su respectivo path. Con esto ejecuta el codigo de 
    # views.detail y y asi crea la ruta de los
     
    
# la url se vera asi 
# NombreDeLaURL_PuestaEn_premiosplatiziapp<int:id>/"<int:id>/detail/naruto"
# ejemplo:
# http://127.0.0.1:8000/preguntas/1//detail/naruto

#/detail/naruto esta de sobra. Sirve para mostrar lo dinamico que es esto.
#Bien solo puede ir <int:id>/ ya que se acede a este atraves del name

# Pero si hago esto con hardcoding debo poner  <int:id>/detail/

    
    
# Function base views
    # path ("<int:id>/", views.detail, name="detail"),
      # Function generic views
      path ("<int:pk>/", views.DetailView.as_view(), name="detail"),
    
    # Function generic views
    # path ("<int:id>/results", views.results, name="results"),
   
    path ("<int:pk>/results", views.ResultsView.as_view(), name="results"),
    
    # Function base views
    path ("<int:id>/vote", views.vote, name="vote"),
    
    
    
]

Basico/Curso Basico de Django/premiosplatziapp/premiosplatziapp/urls.py
from django.contrib import admin
from django.urls import path,include
# from polls.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),   
    # path("", index), 
    ]

Basico/Curso Basico de Django/premiosplatziapp/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date=models.DateField("date published")
    
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes= models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
    

Basico/Curso Basico de Django/premiosplatziapp/polls/views.py
from django.shortcuts import render,get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse
from .models import Question,Choice
from django.urls import reverse
from django.views import generic 
# Create your views here.

# def index(request):
#     lastest_question_list=Question.objects.all()    
#     return render(request, "polls/index.html",{'lastest_question_list':lastest_question_list})

# def detail(request, id):
#     question=get_object_or_404(Question, pk=id)    
#     return render(request, "polls/detail.html", {'question':question})


# def results(request, id):
#     question = get_object_or_404(Question, pk=id)
#     return render(request, 'polls/results.html', {'question': question})
    
    
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
            """Return the last five published questions."""
            return Question.objects.order_by('-pub_date')[:5]
        
        
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
        

def vote(request, id):
    question=get_object_or_404(Question, pk=id)
    # print(f"pregunta: {question }")
    # print(f"pregunta id:{id }")
    # print(f'request.POST["choice"] {request.POST["choice"]}')
    try:
       
        selected_choice= question.choice_set.get(pk=request.POST["choice"])
        
    except (KeyError, Choice.DoesNotExist):
        return render(
            request, 
            "polls/detail.html",
            {"question": question,
             "error_message":"No elegiste una respuesta"})
    else:
        # print(f'selected_choice {selected_choice}')
        # print()
        print(selected_choice)
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(id,)))
    

Basico/Curso Basico de Django/premiosplatziapp/polls/templates/polls/detail.html
<form action="{%  url 'polls:vote' question.id %}" method="post">

    {% csrf_token %}

<fieldset>
    <legend> <h1>{{question.question_text}}</h1> 
    </legend>
    {% if error_message %}
       <p><strong>{{error_message}}</strong></p>
    {% endif %}

    {% for choice in question.choice_set.all %}
        <input 
        type="radio" 
        name="choice" 
        id="choice{{ forloop.counter }}"
        value="{{choice.id}}"
        >
        <label for="choice{{forloop.counter}}">
            {{choice.choice_text}}
        </label>
        <br>
    {% endfor %}    
</fieldset>
<input type="submit" value="Votar">

</form>

{% comment %} <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form> {% endcomment %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{question.question_text}}</h1>
{% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}}</li>
{% endfor %}
</body>
</html> -->

Basico/Curso Basico de Django/premiosplatziapp/polls/templates/polls/index.html
{% if lastest_question_list %}
<ul>
    {% for question in lastest_question_list %}
   


    <li><a href="{% url 'polls:detail' question.id %}"> {{question.question_text}}</a>  </li>
    
    {% endfor %}
</ul>
{% else %}
    <p>No polls disponibles</p>
{% endif %} 

Basico/Curso Basico de Django/premiosplatziapp/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice  in  question.choice_set.all %}
    <li> {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
    {% endfor %}

</ul>
<a href=" {% url 'polls:detail' question.id %}">¿Te gustaria votar de nuevo?</a> 